# Generated by Django 2.2 on 2021-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(default='Deactive', max_length=10),
        ),
    ]
