# Generated by Django 2.2 on 2021-08-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Desc', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category_Name', models.CharField(max_length=100)),
                ('Main_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApanuKhetarApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Brand_Name', models.CharField(max_length=100)),
                ('Product_Desc', models.TextField(max_length=500)),
                ('Product_Price', models.IntegerField()),
                ('Product_Stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_image_1', models.ImageField(default='', upload_to='Product_Images/')),
                ('Product_image_2', models.ImageField(default='', upload_to='Product_Images/')),
                ('Product_image_3', models.ImageField(default='', upload_to='Product_Images/')),
                ('Product_image_4', models.ImageField(default='', upload_to='Product_Images/')),
                ('Discount_Percentage', models.FloatField()),
                ('Discount_Amount', models.FloatField()),
                ('After_Discount', models.FloatField()),
                ('Tax_Percentage', models.FloatField()),
                ('Tax_Amount', models.FloatField()),
                ('Final_Amount', models.FloatField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApanuKhetarApp.Sub_Category')),
            ],
        ),
    ]
