# Generated by Django 2.2 on 2021-08-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0003_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_Desc',
        ),
    ]
