# Generated by Django 2.2 on 2021-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0004_remove_category_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='After_Discount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount_Amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Discount_Percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Final_Amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_1',
            field=models.ImageField(blank=True, default='', upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_2',
            field=models.ImageField(blank=True, default='', upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_3',
            field=models.ImageField(blank=True, default='', upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_4',
            field=models.ImageField(blank=True, default='', upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tax_Amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tax_Percentage',
            field=models.FloatField(blank=True),
        ),
    ]
