# Generated by Django 2.2 on 2021-08-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0005_auto_20210820_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Brand_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
