# Generated by Django 2.2 on 2021-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0007_auto_20210820_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image_1',
            field=models.ImageField(null=True, upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_2',
            field=models.ImageField(null=True, upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_3',
            field=models.ImageField(null=True, upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image_4',
            field=models.ImageField(null=True, upload_to='Product_Images/'),
        ),
    ]
