# Generated by Django 2.2 on 2021-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0009_auto_20210820_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
