# Generated by Django 2.2 on 2021-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0010_sub_category_sub_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='default.png', upload_to='Product_Images/'),
        ),
    ]
