# Generated by Django 2.2 on 2021-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0011_auto_20210820_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='img/default.png', upload_to='Product_Images/'),
        ),
    ]
