# Generated by Django 2.2 on 2021-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0012_auto_20210820_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='default.png', upload_to='Product_Images/'),
        ),
    ]
