# Generated by Django 2.2 on 2021-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0013_auto_20210820_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(default='default.jpg', upload_to='Product_Images/'),
        ),
    ]
