# Generated by Django 2.2 on 2021-08-23 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0015_auto_20210821_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApanuKhetarApp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApanuKhetarApp.User')),
            ],
        ),
    ]
