# Generated by Django 2.2 on 2021-08-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0017_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
