# Generated by Django 2.2 on 2021-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0018_auto_20210827_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
