# Generated by Django 2.2 on 2021-08-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0021_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offer',
        ),
    ]
