# Generated by Django 2.2 on 2021-08-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0025_auto_20210828_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_percentage',
            field=models.CharField(default='', max_length=10),
        ),
    ]
