# Generated by Django 2.2 on 2021-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0026_cart_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='after_dicount_price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
