# Generated by Django 2.2 on 2021-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0027_cart_after_dicount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='after_dicount_price',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_percentage',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
