# Generated by Django 2.2 on 2021-08-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0028_auto_20210828_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Shipping_Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
