# Generated by Django 2.2 on 2021-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0029_auto_20210830_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=500)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
