# Generated by Django 2.2 on 2021-09-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApanuKhetarApp', '0030_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
    ]
